version: '3.5'
services:
  react-expo:
    container_name: react-expo
    image: jungseoro/react-expo
    ports:
    - "19000-19006:19000-19006"
    volumes:
    - ../:/vol
    environment:
    - ADB_IP
    - REACT_NATIVE_PACKAGER_HOSTNAME
    command: |
      sh -c 'expo login -u "${EXPO_USERNAME}" -p "${EXPO_PASSWORD}" \
      && cd /vol \
      && npm install \
      && npm start'
