version: '3.5'
services:
  react-expo:
    container_name: react-native
    image: jungseoro/react-native
    stdin_open: true
    tty: true   
    volumes:
    - ../:/vol
    command: |
      sh -c 'adb pair "${DEVICE_IP}":"${PAIR_PORT}" "${PAIR_CODE}" \
      && adb connect "${DEVICE_IP}":"${DEVICE_PORT}" \
      && cd /vol \
      && npm install \
      && npx react-native start'